---
# tasks file for webserver
- name: Copy aldente public deploy key
  copy: content="{{ aldente_deploy_key.public }}" dest="/home/oppr/.ssh/aldente_deploy_key.pub" mode=0600 owner=oppr

- name: Copy aldente private deploy key
  copy: content="{{ aldente_deploy_key.private }}" dest="/home/oppr/.ssh/aldente_deploy_key" mode=0600 owner=oppr

- name: Install sendmail
  apt: name=sendmail state=latest

- name: Install php-fpm
  apt: name=php7.0-fpm state=latest
  notify: restart php-fpm

- name: Copy php-fpm php.ini
  copy: src=php.ini dest=/etc/php/7.0/fpm/php.ini mode=0644 owner=root
  notify: restart php-fpm

- name: Install nginx
  apt: name=nginx state=latest
  notify: restart nginx

- name: Generate nginx configuration
  template: src=nginx.conf.jinja2 dest=/etc/nginx/nginx.conf mode=0644
  notify: restart nginx

- name: Install static websites
  git: repo={{ item.github }} dest=/home/oppr/{{ item.name }} accept_hostkey=yes force=yes update=yes version=master key_file=/home/oppr/.ssh/{{ item.key if item.key is defined else "id_rsa"}}
  with_items: "{{ static_websites }}"
  tags:
    - static_websites
  become: True
  become_user: oppr
